/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWeekOffsRouteImport } from './routes/_app.week-offs'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPayslipsRouteImport } from './routes/_app.payslips'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppLeavesRouteImport } from './routes/_app.leaves'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppChallansRouteImport } from './routes/_app.challans'
import { Route as AppAttendanceSheetRouteImport } from './routes/_app.attendance-sheet'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekOffsRoute = AppWeekOffsRouteImport.update({
  id: '/week-offs',
  path: '/week-offs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipsRoute = AppPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppLeavesRoute = AppLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppChallansRoute = AppChallansRouteImport.update({
  id: '/challans',
  path: '/challans',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceSheetRoute = AppAttendanceSheetRouteImport.update({
  id: '/attendance-sheet',
  path: '/attendance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/attendance-sheet': typeof AppAttendanceSheetRoute
  '/challans': typeof AppChallansRoute
  '/employees': typeof AppEmployeesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/leaves': typeof AppLeavesRoute
  '/payroll': typeof AppPayrollRoute
  '/payslips': typeof AppPayslipsRoute
  '/settings': typeof AppSettingsRoute
  '/week-offs': typeof AppWeekOffsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/attendance-sheet': typeof AppAttendanceSheetRoute
  '/challans': typeof AppChallansRoute
  '/employees': typeof AppEmployeesRoute
  '/integrations': typeof AppIntegrationsRoute
  '/leaves': typeof AppLeavesRoute
  '/payroll': typeof AppPayrollRoute
  '/payslips': typeof AppPayslipsRoute
  '/settings': typeof AppSettingsRoute
  '/week-offs': typeof AppWeekOffsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/attendance-sheet': typeof AppAttendanceSheetRoute
  '/_app/challans': typeof AppChallansRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/leaves': typeof AppLeavesRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/payslips': typeof AppPayslipsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/week-offs': typeof AppWeekOffsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/attendance-sheet'
    | '/challans'
    | '/employees'
    | '/integrations'
    | '/leaves'
    | '/payroll'
    | '/payslips'
    | '/settings'
    | '/week-offs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/attendance-sheet'
    | '/challans'
    | '/employees'
    | '/integrations'
    | '/leaves'
    | '/payroll'
    | '/payslips'
    | '/settings'
    | '/week-offs'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/attendance-sheet'
    | '/_app/challans'
    | '/_app/employees'
    | '/_app/integrations'
    | '/_app/leaves'
    | '/_app/payroll'
    | '/_app/payslips'
    | '/_app/settings'
    | '/_app/week-offs'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week-offs': {
      id: '/_app/week-offs'
      path: '/week-offs'
      fullPath: '/week-offs'
      preLoaderRoute: typeof AppWeekOffsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payslips': {
      id: '/_app/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AppPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaves': {
      id: '/_app/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AppLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challans': {
      id: '/_app/challans'
      path: '/challans'
      fullPath: '/challans'
      preLoaderRoute: typeof AppChallansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance-sheet': {
      id: '/_app/attendance-sheet'
      path: '/attendance-sheet'
      fullPath: '/attendance-sheet'
      preLoaderRoute: typeof AppAttendanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAttendanceSheetRoute: typeof AppAttendanceSheetRoute
  AppChallansRoute: typeof AppChallansRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLeavesRoute: typeof AppLeavesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPayslipsRoute: typeof AppPayslipsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeekOffsRoute: typeof AppWeekOffsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppAttendanceSheetRoute: AppAttendanceSheetRoute,
  AppChallansRoute: AppChallansRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLeavesRoute: AppLeavesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPayslipsRoute: AppPayslipsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeekOffsRoute: AppWeekOffsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
